# Generated by Django 3.0.3 on 2020-08-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resaurant',
            new_name='Restaurant',
        ),
    ]
